spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crrs
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQrLDialect
application:
  security:
    jwt:
      secret-key: 7638792F423F4528472B4B6250655368566D597133743677397A24432646294A
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days