spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crrs
    username: admin
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect