version: '3.8'
services:
  db:
    image: 'postgres:13.1-alpine'
    container_name: crrs-database
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"