import com.ontime.crrs.rules.order.OrderRequest;
import com.ontime.crrs.rules.model.Rule;
import com.ontime.crrs.rules.util.RuleType;
import com.ontime.crrs.rules.CustomerType;
import com.ontime.crrs.rules.MonitoringSystem;
import com.ontime.crrs.business.menuitem.model.MenuItem;
import com.ontime.crrs.persistence.menuitem.util.Category;
global com.ontime.crrs.rules.order.OrderDiscount orderDiscount;

dialect "mvel"

rule "Quiet Times Discount - All"
    when
        $rule : Rule(ruleType == RuleType.QUIET_TIMES, discountOn == Category.ALL)
        MonitoringSystem(quietTimes == true)
    then
        System.out.println("\n========== Adding QUIET TIMES discount on ALL: " + $rule.discount + "% =============\n");
        orderDiscount.setOverallDiscount($rule.discount);
end

rule "Quiet Times Discount - Item Type"
    when
        $rule : Rule(ruleType == RuleType.QUIET_TIMES)
        MonitoringSystem(quietTimes == true)
    then
        System.out.println("\n========== Adding QUIET TIMES discount on " + $rule.getDiscountOn().name() + " : " + $rule.discount + "% =============\n");
        orderDiscount.setOverallDiscount($rule.discount);
end

rule "Happy Hours Discount"
    when
        $rule : Rule(ruleType == RuleType.HAPPY_HOURS)
    then
        System.out.println("========== Adding HAPPY HOURS discount ... =============");
        orderDiscount.setOverallDiscount($rule.discount);
end

rule "Group Specials Discount"
    when
        $rule : Rule(ruleType == RuleType.GROUP_SPECIALS)
    then
        System.out.println("========== Adding GROUP SPECIALS discount ... =============");
        orderDiscount.setOverallDiscount($rule.discount);
end

rule "Day of Week Discount"
    when
        $rule : Rule(ruleType == RuleType.DAY_OF_WEEK)
    then
        System.out.println("========== Adding DAY OF WEEK discount ... =============");
        orderDiscount.setOverallDiscount($rule.discount);
end